export const FETCH_DATA_REQUEST = 'FETCH_DATA_REQUEST'
export type FETCH_DATA_REQUEST = typeof FETCH_DATA_REQUEST

export const FETCH_DATA_RESPONSE = 'FETCH_DATA_RESPONSE'
export type FETCH_DATA_RESPONSE = typeof FETCH_DATA_RESPONSE

export const FETCH_DATA_ERROR = 'FETCH_DATA_ERROR'
export type FETCH_DATA_ERROR = typeof FETCH_DATA_ERROR
