AWSTemplateFormatVersion: 2010-09-09
Transform:
- AWS::Serverless-2016-10-31
- AWS::CodeStar

Parameters:
  ProjectId:
    Type: String
    Description:
      AWS CodeStar projectID used to associate new resources to team members
  CognitoUserPoolId:
    Type: String
    Description: ARN of the user pool to be used for authorized requests
  DbTablePrefix:
    Type: String
    Description: Prefix to be used for all database tables

Resources:

  # Database tables
  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Join ['', [!Ref 'DbTablePrefix', 'users']]
      AttributeDefinitions:
        -
          AttributeName: "id"
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: "id"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: "3"
        WriteCapacityUnits: "3"
  SquadsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Join ['', [!Ref 'DbTablePrefix', 'squads']]
      AttributeDefinitions:
        -
          AttributeName: "id"
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: "id"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: "3"
        WriteCapacityUnits: "3"
  TournamentsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Join ['', [!Ref 'DbTablePrefix', 'tournaments']]
      AttributeDefinitions:
        -
          AttributeName: "id"
          AttributeType: "N"
      KeySchema:
        -
          AttributeName: "id"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: "2"
        WriteCapacityUnits: "2"
  MatchDaysTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Join ['', [!Ref 'DbTablePrefix', 'match-days']]
      AttributeDefinitions:
        -
          AttributeName: "tournament_id"
          AttributeType: "N"
        -
          AttributeName: "id"
          AttributeType: "N"
      KeySchema:
        -
          AttributeName: "tournament_id"
          KeyType: "HASH"
        -
          AttributeName: "id"
          KeyType: "RANGE"
      ProvisionedThroughput:
        ReadCapacityUnits: "3"
        WriteCapacityUnits: "3"
  MatchesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Join ['', [!Ref 'DbTablePrefix', 'matches']]
      AttributeDefinitions:
        -
          AttributeName: "match_day_id"
          AttributeType: "N"
        -
          AttributeName: "id"
          AttributeType: "N"
      KeySchema:
        -
          AttributeName: "match_day_id"
          KeyType: "HASH"
        -
          AttributeName: "id"
          KeyType: "RANGE"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "3"
  BetsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Join ['', [!Ref 'DbTablePrefix', 'bets']]
      AttributeDefinitions:
        -
          AttributeName: "squad_id"
          AttributeType: "S"
        -
          AttributeName: "match_day_id"
          AttributeType: "N"
      KeySchema:
        -
          AttributeName: "squad_id"
          KeyType: "HASH"
        -
          AttributeName: "match_day_id"
          KeyType: "RANGE"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"

  # Authorizer for the API Gateway
  CognitoAuthorizer:
    Type: AWS::ApiGateway::Authorizer
    Properties:
      Type: COGNITO_USER_POOLS
      Name: CognitoAuthorizer
      IdentitySource: method.request.header.Authorization
      ProviderARNs: [!Ref 'CognitoUserPoolId']
      RestApiId: !Ref 'ServerlessRestApi'

  # Backend Lambdas
  DataProvider:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambdas/dist/get_data
      Runtime: go1.x
      Role:
        Fn::ImportValue:
          !Join ['-', [!Ref 'ProjectId', !Ref 'AWS::Region', 'LambdaTrustRole']]
      Events:
        GetTournaments:
          Type: Api
          Properties:
            Path: /tournaments
            Method: get
        GetTournamentById:
          Type: Api
          Properties:
            Path: /tournaments/{tournamentId}
            Method: get
        GetMatchDayById:
          Type: Api
          Properties:
            Path: /match-days/{matchDayId}
            Method: get
        GetBetsByMatchDayIdAndSquad:
          Type: Api
          Properties:
            Path: /match-days/{matchDayId}/bets/{squadName}
            Method: get
  SessionManager:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambdas/dist/get_session
      Runtime: go1.x
      Role:
        Fn::ImportValue:
          !Join ['-', [!Ref 'ProjectId', !Ref 'AWS::Region', 'LambdaTrustRole']]
      Events:
        MeOptions:
          Type: Api
          Properties:
            Path: /me
            Method: options
        GetMe:
          Type: Api
          Properties:
            Path: /me
            Method: get
