AWSTemplateFormatVersion: 2010-09-09
Transform:
- AWS::Serverless-2016-10-31
- AWS::CodeStar

Parameters:
  ProjectId:
    Type: String
    Description:
      AWS CodeStar projectID used to associate new resources to team members
  CognitoUserPoolId:
    Type: String
    Description: ARN of the user pool to be used for authorized requests
  DbTablePrefix:
    Type: String
    Description: Prefix to be used for all database tables

Resources:

  # Database tables
  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Join ['', [!Ref 'DbTablePrefix', 'users']]
      AttributeDefinitions:
        -
          AttributeName: "id"
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: "id"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: "1"
        WriteCapacityUnits: "1"
  SquadsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Join ['', [!Ref 'DbTablePrefix', 'squads']]
      AttributeDefinitions:
        -
          AttributeName: "id"
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: "id"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: "2"
        WriteCapacityUnits: "2"
  TournamentsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Join ['', [!Ref 'DbTablePrefix', 'tournaments']]
      AttributeDefinitions:
        -
          AttributeName: "id"
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: "id"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: "3"
        WriteCapacityUnits: "3"
  MatchDaysTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Join ['', [!Ref 'DbTablePrefix', 'match-days']]
      AttributeDefinitions:
        -
          AttributeName: "tournament_id"
          AttributeType: "S"
        -
          AttributeName: "id"
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: "tournament_id"
          KeyType: "HASH"
        -
          AttributeName: "id"
          KeyType: "RANGE"
      ProvisionedThroughput:
        ReadCapacityUnits: "3"
        WriteCapacityUnits: "3"
  MatchesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Join ['', [!Ref 'DbTablePrefix', 'matches']]
      AttributeDefinitions:
        -
          AttributeName: "tournament_and_match_day_id"
          AttributeType: "S"
        -
          AttributeName: "id"
          AttributeType: "N"
      KeySchema:
        -
          AttributeName: "tournament_and_match_day_id"
          KeyType: "HASH"
        -
          AttributeName: "id"
          KeyType: "RANGE"
      ProvisionedThroughput:
        ReadCapacityUnits: "3"
        WriteCapacityUnits: "3"
  BetsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Join ['', [!Ref 'DbTablePrefix', 'bets']]
      AttributeDefinitions:
        -
          AttributeName: "squad_id"
          AttributeType: "S"
        -
          AttributeName: "tournament_and_match_day_id"
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: "squad_id"
          KeyType: "HASH"
        -
          AttributeName: "tournament_and_match_day_id"
          KeyType: "RANGE"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
  PoolsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Join ['', [!Ref 'DbTablePrefix', 'pools']]
      AttributeDefinitions:
        -
          AttributeName: "squad_id"
          AttributeType: "S"
        -
          AttributeName: "tournament_id"
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: "squad_id"
          KeyType: "HASH"
        -
          AttributeName: "tournament_id"
          KeyType: "RANGE"
      ProvisionedThroughput:
        ReadCapacityUnits: "2"
        WriteCapacityUnits: "2"
  ExtraBetsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Join ['', [!Ref 'DbTablePrefix', 'extra-bets']]
      AttributeDefinitions:
        -
          AttributeName: "squad_id"
          AttributeType: "S"
        -
          AttributeName: "tournament_id"
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: "squad_id"
          KeyType: "HASH"
        -
          AttributeName: "tournament_id"
          KeyType: "RANGE"
      ProvisionedThroughput:
        ReadCapacityUnits: "2"
        WriteCapacityUnits: "2"
  TeamsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Join ['', [!Ref 'DbTablePrefix', 'teams']]
      AttributeDefinitions:
        -
          AttributeName: "tournament_id"
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: "tournament_id"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: "2"
        WriteCapacityUnits: "2"

  # Authorizer for the API Gateway
  CognitoAuthorizer:
    Type: AWS::ApiGateway::Authorizer
    Properties:
      Type: COGNITO_USER_POOLS
      Name: CognitoAuthorizer
      IdentitySource: method.request.header.Authorization
      ProviderARNs: [!Ref 'CognitoUserPoolId']
      RestApiId: !Ref 'ServerlessRestApi'

  # Backend Lambdas
  DataProvider:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambdas/dist/get_data
      Runtime: go1.x
      Role:
        Fn::ImportValue:
          !Join ['-', [!Ref 'ProjectId', !Ref 'AWS::Region', 'LambdaTrustRole']]
      Events:
        GetTournaments:
          Type: Api
          Properties:
            Path: /tournaments
            Method: get
        GetTournamentById:
          Type: Api
          Properties:
            Path: /tournaments/{tournamentId}
            Method: get
        GetMatchDayById:
          Type: Api
          Properties:
            Path: /tournaments/{tournamentId}/match-days/{matchDayId}
            Method: get
        GetBetsByMatchDayIdAndSquadAsGuest:
          Type: Api
          Properties:
            Path: /tournaments/{tournamentId}/match-days/{matchDayId}/bets/{squadId}
            Method: get
        GetBetsByMatchDayIdAndSquadAsUser:
          Type: Api
          Properties:
            Path: /tournaments/{tournamentId}/match-days/{matchDayId}/bets/{squadId}/mine
            Method: get
        SubmitBet:
          Type: Api
          Properties:
            Path: /tournaments/{tournamentId}/match-days/{matchDayId}/bets/{squadId}/mine
            Method: post
        SubmitBetOptions:
          Type: Api
          Properties:
            Path: /tournaments/{tournamentId}/match-days/{matchDayId}/bets/{squadId}/mine
            Method: options
        GetPoolById:
          Type: Api
          Properties:
            Path: /tournaments/{tournamentId}/pools/{squadId}
            Method: get
        JoinPoolById:
          Type: Api
          Properties:
            Path: /tournaments/{tournamentId}/pools/{squadId}
            Method: post
        JoinPoolOptions:
          Type: Api
          Properties:
            Path: /tournaments/{tournamentId}/pools/{squadId}
            Method: options
        GetSquadById:
          Type: Api
          Properties:
            Path: /squads/{squadId}
            Method: get
        JoinSquadById:
          Type: Api
          Properties:
            Path: /squads/{squadId}
            Method: post
        JoinSquadOptions:
          Type: Api
          Properties:
            Path: /squads/{squadId}
            Method: options
        GetExtraQuestions:
          Type: Api
          Properties:
            Path: /tournaments/{tournamentId}/pools/{squadId}/extra-questions
            Method: get
        SubmitExtraQuestionBet:
          Type: Api
          Properties:
            Path: /tournaments/{tournamentId}/pools/{squadId}/extra-questions
            Method: post
        SubmitExtraQuestionBetOptions:
          Type: Api
          Properties:
            Path: /tournaments/{tournamentId}/pools/{squadId}/extra-questions
            Method: options
  SessionManager:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambdas/dist/get_session
      Runtime: go1.x
      Role:
        Fn::ImportValue:
          !Join ['-', [!Ref 'ProjectId', !Ref 'AWS::Region', 'LambdaTrustRole']]
      Events:
        MeOptions:
          Type: Api
          Properties:
            Path: /me
            Method: options
        GetMe:
          Type: Api
          Properties:
            Path: /me
            Method: get
        PreferredNameOptions:
          Type: Api
          Properties:
            Path: /me/preferred-name
            Method: options
        PostPreferredName:
          Type: Api
          Properties:
            Path: /me/preferred-name
            Method: post
  Admin:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambdas/dist/admin
      Runtime: go1.x
      Role:
        Fn::ImportValue:
          !Join ['-', [!Ref 'ProjectId', !Ref 'AWS::Region', 'LambdaTrustRole']]
      Events:
        UpdateMatchOptions:
          Type: Api
          Properties:
            Path: /tournaments/{tournamentId}/match-days/{matchDayId}/matches/{matchId}
            Method: options
        UpdateMatch:
          Type: Api
          Properties:
            Path: /tournaments/{tournamentId}/match-days/{matchDayId}/matches/{matchId}
            Method: post
